name: fastapi-app

on:
  push:
    branches:
      - main
      - Feature/**
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Ensures job fails if it runs too long

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m venv venv
          venv/bin/python -m pip install --upgrade pip
          venv/bin/python -m pip install -r requirements.txt

      - name: Run Linter (flake8)
        run: |
          venv/bin/python -m pip install flake8
          venv/bin/python -m flake8 . --ignore=E501

      - name: Run tests
        run: |
          venv/bin/python -m pytest --maxfail=1 --disable-warnings --timeout=30 || exit 1
